# fly.toml app configuration file generated for feat-upload-studio on 2024-01-30T09:38:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feat-upload-studio"
primary_region = "fra"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
